POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Tangkas",
    "email": "tr@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "tr@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/getAdmin/1

###
DELETE http://localhost:5000/logout